security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        api_token_provider:
            id: App\Infrastructure\Security\ApiTokenUserProvider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        login:
            pattern: ^/api/login$
            security: false
        web_login:
            pattern: $/api/login$
            security: false
        web:
            pattern: ^/web/
            stateless: false
            custom_authenticators:
                - App\Infrastructure\Security\WebSessionAuthenticator
        web_sync:
            pattern: ^/web/sync-users$
            security: false
        api:
            pattern: ^/
            stateless: true
            custom_authenticators:
                - App\Infrastructure\Security\ApiTokenAuthenticator
        graphql:
            pattern: $/graphql
            stateless: true
            custom_authenticators:
                - App\Infrastructure\Security\ApiTokenAuthenticator

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/web/login, roles: PUBLIC_ACCESS }
        - { path: ^/web/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/web/sync-users, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/graphql, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
