TaskEvent:
    type: object
    config:
        fields:
            id:
                type: "Int!"
            taskId:
                type: "String!"
            eventType:
                type: "String!"
            payload:
                type: "String!"
            occurredAt:
                type: "String!"
