User:
    type: object
    config:
        fields:
            id:
                type: "String!"
            name:
                type: "String!"
            email:
                type: "String!"
            phone:
                type: "String!"
            username:
                type: "String"
            roles:
                type: "[String]!"
            externalId:
                type: "Int"
